### ISSUE TITLE
Ask for permission

### ISSUE THREAD

**Issue by zh-f** [gizak/gizak.github.io#3]
First of all , your work is so awesome! It's your website let me start to know clojure, and it's so fun. 
So i think i have to thank you and ask about: 
Can i fork this repository and build my own website based on your awesome work?

**Comment by gizak** [comment]
You are free to use any codes for your projects! But be warned that I did not make a lot of tests on it ;)

**Comment by zh-f** [comment]
Great! 
Em...to be honest, i have no idea how I can _build_ my website using your codes :(  Changing content such as 

``` clojure
(cmd/register :github "goto my github page"
              (fn [opts]
                (open-link "https://github.com/gizak"))) ;; change into https://github.com/2hf
```

did not work.
Hope my idiot question do not bother you. And I really appreciate it if you can guide a way for me :+1:

**Comment by gizak** [comment]
No problem. Clojurescript is the kind of language that you have to compile. Here I use a Clojure tool called boot which can compile CLJS to js. If you have made any changes on cljs codes, then in order to make it effect, you need to `boot test` or `boot prod` (I defend it at `build.boot`)

For more info about boot, go to http://boot-clj.com. 

Using Clojurescript is fun and painful.

**Comment by 2hf** [comment]
Hi, sorry to bother you again. After I `boot prod` and I got a folder named `build`. What should I do then ? Committing all files of `build` is not working. Replacing files is not working, neither. How can I deploy this  website on my github? I just do not have a clue. Seems I am totally a newbie. It hurts.

**Comment by zh-f** [comment]
Thanks so much for your patient explanation. I finally rebuild my website and deploy it on my Github. Still working on it. Thanks again! :smiley:
